import { notFound } from "next/navigation";
import Link from "next/link";
import { getFarm, sampleFarms } from "@/lib/sample-farms";
import { Wheat, Sun, Jar, Leaf, Barn } from "@/components/mark";

export function generateStaticParams() {
  return sampleFarms.map((f) => ({ slug: f.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const farm = getFarm(slug);
  if (!farm) return {};
  return {
    title: `${farm.name} — ${farm.location}`,
    description: farm.tagline,
  };
}

export default async function FarmPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const farm = getFarm(slug);
  if (!farm) notFound();

  return (
    <div>
      {/* Notice this is a generated farm homepage */}
      <div className="bg-soil text-parchment/85 text-xs text-center py-2 small-caps">
        Sample farm homepage · generated by Communicare ·{" "}
        <Link href="/homepage" className="text-wheat hover:underline">
          make one for your farm →
        </Link>
      </div>

      {/* HERO */}
      <section className="relative overflow-hidden border-b border-soil/15">
        <div className="absolute inset-0 bg-grain opacity-30 pointer-events-none" />
        <div className="max-w-page mx-auto px-6 pt-16 md:pt-24 pb-20 relative">
          <div className="flex items-center gap-3 mb-8">
            <FarmHero kind={farm.kind} />
            <div className="small-caps text-xs text-brick">{farm.kind}</div>
          </div>
          <h1 className="display text-5xl md:text-7xl font-medium leading-[0.95] max-w-4xl">
            {farm.name}
          </h1>
          <div className="mt-4 display italic text-xl md:text-2xl text-soil/65">
            {farm.location}
          </div>
          <p className="mt-8 max-w-2xl text-xl md:text-2xl leading-relaxed text-soil/85">
            {farm.tagline}
          </p>
          <div className="mt-10 flex flex-wrap gap-3">
            <Link href={`/farm/${farm.slug}/subscribe/`} className="btn btn-primary">
              Subscribe to a share →
            </Link>
            <Link href={`/farm/${farm.slug}/journal/`} className="btn btn-ghost">
              Read the farm journal
            </Link>
          </div>
        </div>
      </section>

      {/* THE STORY */}
      <section className="border-b border-soil/15 bg-cream">
        <div className="max-w-3xl mx-auto px-6 py-24">
          <div className="small-caps text-xs text-brick mb-4">Our story</div>
          <h2 className="display text-4xl md:text-5xl font-medium leading-[1.1] mb-10">
            About {farm.name}.
          </h2>
          <div className="text-soil/60 text-sm display italic mb-6">
            ✎ {farm.founder} — {farm.founderBio}
          </div>
          <p className="drop-cap text-xl leading-relaxed text-soil/85">
            {farm.story}
          </p>
        </div>
      </section>

      {/* CALLOUTS */}
      <section className="max-w-page mx-auto px-6 py-24">
        <div className="grid md:grid-cols-3 gap-10 max-w-5xl mx-auto">
          {farm.callouts.map((c, i) => (
            <div key={i}>
              <div className="small-caps text-xs text-wheat mb-3">№ {i + 1}</div>
              <h3 className="display text-2xl font-medium mb-3 leading-tight">
                {c.label}
              </h3>
              <p className="text-soil/80 leading-relaxed">{c.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* SHARE / SUBSCRIBE */}
      <section
        id="join"
        className="bg-soil text-parchment relative overflow-hidden border-t border-b border-soil"
      >
        <div className="absolute inset-0 bg-grain opacity-25 pointer-events-none" />
        <div className="max-w-3xl mx-auto px-6 py-24 relative">
          <div className="text-center mb-12">
            <div className="small-caps text-xs text-wheat mb-3">
              Subscribe to the share
            </div>
            <h2 className="display text-4xl md:text-5xl font-medium">
              {farm.share.name}
            </h2>
            <div className="display italic text-parchment/70 mt-3 text-lg">
              {farm.share.cadence}
            </div>
            <div className="display text-3xl text-wheat mt-6">
              {farm.share.price}
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-8 mb-12">
            <div>
              <div className="small-caps text-xs text-wheat mb-3">
                What's included
              </div>
              <ul className="space-y-3">
                {farm.share.includes.map((item, i) => (
                  <li key={i} className="flex gap-3 text-parchment/85">
                    <span className="text-wheat">※</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <div className="small-caps text-xs text-wheat mb-3">
                Pickup days & places
              </div>
              <ul className="space-y-3">
                {farm.pickup.map((p, i) => (
                  <li key={i}>
                    <div className="display text-parchment">{p.place}</div>
                    <div className="text-sm text-parchment/65">
                      {p.day}, {p.window}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="grid sm:grid-cols-[1fr_auto] gap-3">
            <input
              type="email"
              placeholder="your email — we'll send a magic link"
              className="bg-parchment/10 border border-parchment/30 text-parchment placeholder-parchment/45 px-4 py-3.5 rounded font-body focus:outline-none focus:border-wheat"
            />
            <button
              type="button"
              className="btn bg-wheat text-soil border-wheat hover:bg-parchment hover:border-parchment"
            >
              Sign me up →
            </button>
          </div>
          <div className="text-center text-parchment/55 text-sm italic mt-4">
            No password to remember. We'll text you when your share is ready.
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-3xl mx-auto px-6 py-24">
        <div className="small-caps text-xs text-brick mb-4">
          Things you might be wondering
        </div>
        <h2 className="display text-4xl md:text-5xl font-medium mb-10">
          Questions, asked &amp; answered.
        </h2>
        <div className="space-y-8">
          {farm.faq.map((q, i) => (
            <div key={i} className="border-b border-soil/15 pb-8 last:border-0">
              <div className="display text-xl font-medium mb-3 text-soil">
                {q.q}
              </div>
              <p className="text-soil/80 leading-relaxed">{q.a}</p>
            </div>
          ))}
        </div>
      </section>

      <div className="ornament mb-16 max-w-md mx-auto">❦ ◊ ❦</div>

      <div className="text-center text-soil/55 text-sm pb-12">
        {farm.name} runs on{" "}
        <Link href="/" className="text-brick hover:underline">
          Communicare
        </Link>{" "}
        — $9/month, made as a gift.
      </div>
    </div>
  );
}

function FarmHero({ kind }: { kind: string }) {
  if (kind === "Raw milk herd share")
    return <Jar className="w-9 h-12 text-brick" />;
  if (kind === "Pastured meat") return <Barn className="w-11 h-9 text-brick" />;
  if (kind === "Vegetable CSA") return <Leaf className="w-10 h-10 text-mossDark" />;
  return <Wheat className="w-8 h-11 text-wheatDark" />;
}
